import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/header/navbar';
import { ToastProvider } from './providers/toast-provider';
import MySessionProvider from './providers/session-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <MySessionProvider>
          <ToastProvider />
          <main className='h-screen flex flex-col justify-center items-center'>
            <Navbar />
            {children}
          </main>
        </MySessionProvider>
      </body>
    </html>
  );
}
